import type { AppState, BudgetSummary, DetectionResult, PremiumImprovementOpportunity, PremiumPlanAlternative, PremiumValueSummary } from '../types';
import { calculateBudgetHealth } from './budgetHealth';

function finite(value: number, fallback = 0) { return Number.isFinite(value) ? value : fallback; }
function clamp(value: number, min: number, max: number) { return Math.max(min, Math.min(max, finite(value))); }
function monthlyIncome(summary: BudgetSummary) { return Math.max(0, finite(summary.totalIncome)); }
function hashMetrics(summary: BudgetSummary, state: AppState, detection: DetectionResult) {
  return JSON.stringify({ i: Math.round(summary.totalIncome), f: Math.round(summary.fixedTotal), v: Math.round(summary.variablePlanTotal), m: Math.round(summary.remainingAfterPlan), r: detection.reviewItems.length, d: state.recurringDecisions, g: state.premiumGoals });
}
function opportunity(input: Omit<PremiumImprovementOpportunity, 'estimationNote'> & { estimationNote?: string }): PremiumImprovementOpportunity {
  return { estimationNote: input.estimatedMarginImpact > 0 ? 'Uppskattad möjlig effekt baserad på din nuvarande Budget. Inte en garanterad besparing.' : 'Detta förbättrar främst tillförlitlighet eller motståndskraft, inte fri marginal direkt.', ...input, estimatedMarginImpact: Math.max(0, Math.round(finite(input.estimatedMarginImpact))), estimatedBudgetHealthImpact: clamp(Math.round(finite(input.estimatedBudgetHealthImpact)), 0, 20) };
}

export function buildPremiumValueSummary(input: { state: AppState; summary: BudgetSummary; detection: DetectionResult; visibleReviewCount?: number; duplicateIncomeCount?: number }): PremiumValueSummary {
  const { state, summary, detection } = input;
  const income = monthlyIncome(summary);
  const margin = finite(summary.remainingAfterPlan);
  const fixedShare = income > 0 ? summary.fixedTotal / income : 0;
  const availableAfterFixed = finite(summary.remainingAfterFixed);
  const variableShareOfAvailable = availableAfterFixed > 0 ? summary.variablePlanTotal / availableAfterFixed : 0;
  const health = calculateBudgetHealth({ summary, detection, state, visibleReviewCount: input.visibleReviewCount || 0 });
  const opportunities: PremiumImprovementOpportunity[] = [];
  if (margin < 0) opportunities.push(opportunity({ id: 'negative-margin', type: 'margin_risk', title: 'Budgeten går under noll', explanation: 'Din planerade Budget saknar marginal just nu. Första steget är att hitta en trygg justering innan andra mål prioriteras.', priority: 100, sourceReasonIds: ['negative_margin'], destination: 'plan', relevantBudgetArea: 'Marginal', estimatedMarginImpact: Math.min(Math.abs(margin), Math.max(300, summary.variablePlanTotal * 0.12)), estimatedBudgetHealthImpact: 14, confidence: 'high', suggestedAction: 'Visa tre alternativa planer', suggestedBuddyMessage: 'Visa tre alternativa planer för att få Budgeten över noll utan att ändra något direkt.' }));
  else if (income > 0 && margin / income < 0.08) opportunities.push(opportunity({ id: 'thin-margin', type: 'thin_margin', title: 'Bygg en tryggare marginal', explanation: 'Marginalen är tunn i förhållande till inkomsten. En liten planerad justering kan göra Budgeten mindre sårbar.', priority: 85, sourceReasonIds: ['thin_margin'], destination: 'variablePlan', relevantBudgetArea: 'Rörliga utgifter', estimatedMarginImpact: Math.min(Math.max(300, income * 0.03), Math.max(0, summary.variablePlanTotal * 0.1)), estimatedBudgetHealthImpact: 9, confidence: 'medium', suggestedAction: 'Se trygg plan', suggestedBuddyMessage: 'Skapa en trygg förbättringsplan för min marginal.' }));
  if (income > 0 && fixedShare > 0.62) opportunities.push(opportunity({ id: 'high-fixed-share', type: 'fixed_share', title: 'Granska fasta utgifter', explanation: 'Fasta utgifter tar en stor del av inkomsten. Det här är ett område att granska, inte en garanterad besparing.', priority: 75, sourceReasonIds: ['high_fixed_share'], destination: 'musts', relevantBudgetArea: 'Fasta utgifter', estimatedMarginImpact: Math.min(Math.max(0, summary.fixedTotal - income * 0.62), summary.fixedTotal * 0.05), estimatedBudgetHealthImpact: 7, confidence: 'low', suggestedAction: 'Granska fasta utgifter', suggestedBuddyMessage: 'Hjälp mig granska fasta utgifter utan att anta att något kan sägas upp.' }));
  if (variableShareOfAvailable > 0.88 || (!summary.variableItems.some(i => /spar|buffert/i.test(i.label + i.category)) && income > 0)) opportunities.push(opportunity({ id: 'variable-buffer', type: 'buffer', title: 'Skapa buffert i rörliga utgifter', explanation: 'Rörliga utgifter lämnar lite utrymme för buffert. En buffert kan minska fri marginal kortsiktigt men stärka Budgeten.', priority: 70, sourceReasonIds: ['no_buffer_or_high_variable_share'], destination: 'variablePlan', relevantBudgetArea: 'Rörliga utgifter', estimatedMarginImpact: variableShareOfAvailable > 0.88 ? Math.min(summary.variablePlanTotal * 0.08, Math.max(0, availableAfterFixed * 0.08)) : 0, estimatedBudgetHealthImpact: 8, confidence: 'medium', suggestedAction: 'Se balanserad plan', suggestedBuddyMessage: 'Föreslå en balanserad rörlig Budget med buffert.' }));
  const duplicateCount = input.duplicateIncomeCount || 0;
  if (duplicateCount > 0) opportunities.push(opportunity({ id: 'duplicate-income', type: 'income_reliability', title: 'Kontrollera möjlig dubbel inkomst', explanation: 'Möjlig dubbelräkning gör Budgeten mindre tillförlitlig. Det räknas inte som en möjlig marginalförbättring.', priority: 90, sourceReasonIds: ['duplicate_income'], destination: 'income', relevantBudgetArea: 'Inkomster', estimatedMarginImpact: 0, estimatedBudgetHealthImpact: 10, confidence: 'high', suggestedAction: 'Granska inkomster', suggestedBuddyMessage: 'Hjälp mig kontrollera möjlig dubbelräkning av inkomst.' }));
  const reviewCount = input.visibleReviewCount ?? detection.reviewItems.length;
  if (reviewCount > 0) opportunities.push(opportunity({ id: 'unresolved-review', type: 'review_reliability', title: 'Rensa oklara poster', explanation: 'Oklara poster kan påverka Budgetens tillförlitlighet. Att granska dem är inte en garanterad besparing.', priority: 65, sourceReasonIds: ['unresolved_review'], destination: 'review', relevantBudgetArea: 'Import & granskning', estimatedMarginImpact: 0, estimatedBudgetHealthImpact: Math.min(8, reviewCount * 2), confidence: 'high', suggestedAction: 'Granska oklara poster', suggestedBuddyMessage: 'Prioritera mina oklara poster och förklara vad som påverkar Budgeten.' }));
  if (!state.householdProfile) opportunities.push(opportunity({ id: 'missing-household', type: 'setup_reliability', title: 'Komplettera hushållsprofil', explanation: 'Hushållsprofilen gör rörliga utgifter mer relevanta för din Budget.', priority: 50, sourceReasonIds: ['missing_household'], destination: 'household', relevantBudgetArea: 'Hushåll', estimatedMarginImpact: 0, estimatedBudgetHealthImpact: 5, confidence: 'medium', suggestedAction: 'Fyll i hushåll', suggestedBuddyMessage: 'Hjälp mig komplettera hushållsprofilen.' }));
  const selected = [...opportunities].sort((a, b) => b.priority - a.priority || b.estimatedBudgetHealthImpact - a.estimatedBudgetHealthImpact || a.id.localeCompare(b.id)).slice(0, 3);
  const estimatedMonthlyMarginPotential = Math.round(selected.reduce((sum, item) => sum + item.estimatedMarginImpact, 0));
  const estimatedBudgetHealthPotential = clamp(selected.reduce((sum, item) => sum + item.estimatedBudgetHealthImpact, 0), 0, 20);
  const suggestedFirstGoal = margin < 0 ? 'Få Budgeten över noll' : margin / Math.max(income, 1) < 0.1 ? 'Bygg 10 % marginal' : reviewCount > 0 ? 'Rensa oklara poster' : 'Behåll en stabil Budgethälsa';
  const activeGoals = state.premiumGoals?.filter(g => g.status === 'active') || [];
  const snapshots = state.premiumSnapshots || [];
  const previous = snapshots.length ? snapshots[snapshots.length - 1] : undefined;
  const marginChange = previous ? summary.remainingAfterPlan - previous.remainingAfterPlan : 0;
  const fixedChange = previous ? summary.fixedTotal - previous.fixedTotal : 0;
  const healthChange = previous ? health.score - previous.budgetHealthScore : 0;
  return { opportunityCount: selected.length, estimatedMonthlyMarginPotential, estimatedBudgetHealthPotential, topOpportunity: selected[0], reviewAreaCount: reviewCount + duplicateCount + selected.filter(o => o.type === 'fixed_share').length, suggestedFirstGoal, currentGoalSummary: activeGoals.length ? `${activeGoals.length} aktivt mål · nästa: ${activeGoals[0].title}` : `Föreslaget mål: ${suggestedFirstGoal}`, developmentSummary: previous ? `Marginal ${marginChange >= 0 ? 'upp' : 'ner'} ${Math.abs(Math.round(marginChange)).toLocaleString('sv-SE')} kr sedan senaste nuläge.` : 'Spara ett nuläge för att följa utvecklingen över tid.', monitoringSummary: state.premiumMonitoring?.enabled ? `Lokal koll aktiv · senaste: ${state.premiumMonitoring.lastRunAt || 'inte körd ännu'}` : 'Automatisk lokal koll är inte aktiverad.', strongestPositiveChange: previous && (marginChange > 0 || fixedChange < 0 || healthChange > 0) ? (marginChange >= Math.abs(fixedChange) ? `Marginalen har förbättrats med ${Math.round(marginChange).toLocaleString('sv-SE')} kr.` : `Fasta utgifter har minskat med ${Math.round(Math.abs(fixedChange)).toLocaleString('sv-SE')} kr.`) : undefined, strongestNegativeChange: previous && (marginChange < 0 || fixedChange > 0 || healthChange < 0) ? (marginChange < 0 ? `Marginalen har försämrats med ${Math.round(Math.abs(marginChange)).toLocaleString('sv-SE')} kr.` : `Fasta utgifter har ökat med ${Math.round(fixedChange).toLocaleString('sv-SE')} kr.`) : undefined, opportunities: selected, alternatives: buildPremiumPlanAlternatives(summary, selected), basedOnMetricsHash: hashMetrics(summary, state, detection) };
}

export function buildPremiumPlanAlternatives(summary: BudgetSummary, opportunities: PremiumImprovementOpportunity[]): PremiumPlanAlternative[] {
  const potential = opportunities.reduce((sum, item) => sum + item.estimatedMarginImpact, 0);
  const modes: Array<[PremiumPlanAlternative['mode'], string, number, string[]]> = [
    ['safe', 'Trygg', 0.55, ['Mer buffert och stabilitet', 'Långsammare marginalförbättring']],
    ['balanced', 'Balanserad', 0.75, ['Jämn avvägning mellan marginal och vardag', 'Kräver några tydliga val']],
    ['ambitious', 'Mer offensiv', 1, ['Snabbare uppskattad marginaleffekt', 'Mindre utrymme för vardagsflexibilitet']],
  ];
  return modes.map(([mode, label, factor, tradeoffs]) => ({ id: `alt_${mode}`, mode, label, summary: `${label}: prioriterar ${opportunities.map(o => o.relevantBudgetArea).slice(0, 2).join(' och ') || 'stabil Budget'}.`, opportunities: opportunities.map(o => o.id), estimatedMargin: Math.round(summary.remainingAfterPlan + potential * factor), estimatedHealthDirection: factor >= 1 ? 'kan förbättra tydligt' : factor > 0.6 ? 'kan förbättra stegvis' : 'kan förbättra försiktigt', tradeoffs, affectedCategories: [...new Set(opportunities.map(o => o.relevantBudgetArea))] }));
}
